In [8]:
"""Import Libraries"""
import pandas as pd
import numpy as np

import bokeh
import seaborn as sns
from matplotlib import pyplot as plt

ModuleNotFoundError: No module named 'seaborn'

In [5]:
"""Open Database"""
Data = pd.read_csv("Databases_CABANA_2.csv", sep = ",")
Data.head()

,Unnamed: 0,ID Database,Name,SMILES,HBA,HBD,RB,LogP,TPSA,MW,Heavy Atom,Ring Count,Fraction CSP3,subLibrary,Library
0,0,AfroDb.564,NPR_00036,CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC(OC...,7.0,3.0,51.0,22.4139,105.45,1194.003,85.0,85.0,85.0,AFRODB,AFRODB
1,1,AfroDb.71,ABD_UD_004,C[C@H](CCC(O[C@H](C[C@@H]([C@@H]1CC2)[C@H]3[C@...,27.0,14.0,18.0,-3.5356,418.89,1195.309,83.0,83.0,83.0,AFRODB,AFRODB
2,2,AfroDb.70,ABD_UD_003,C[C@H](CC[C@@]([C@H]1C)(OC)O[C@H](C2)[C@H]1[C@...,26.0,14.0,17.0,-2.6588,393.98,1195.353,83.0,83.0,83.0,AFRODB,AFRODB
3,3,AfroDb.937,WA_0086,COc(cc(/C=C/C(OCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC...,11.0,3.0,61.0,16.9936,201.42,1117.597,79.0,79.0,79.0,AFRODB,AFRODB
4,4,AfroDb.936,WA_0085,COc(cc(/C=C/C(OCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC...,8.0,3.0,52.0,17.0180,122.52,943.489,67.0,67.0,67.0,AFRODB,AFRODB

In [3]:
# create bar 
p = BoxPlot(df, values = "HBA", label = "Category",  
            color = "yellow", title = "Protein Summary (grouped by category)", 
             legend = "top_right") 
  
# show the results 
show(p)

NameError: name 'BoxPlot' is not defined